### ISSUE TITLE
Import SOWNBot codebase into GitHub

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#12]
This is currently in SVN.  The best plan would be to create a new local Git repository.  Copy the files across as needed and sanitize them for secrets before committing.  Once we were happy we have a sanitised and working copy in Git we should then push to a public GitHub repo.

**Comment by drn05r** [comment]
There is now a private repository at https://github.com/sown/sownbot/

I am fairly confident it does not have any secrets committed but it may be worth keeping it private for a while to allow a few more people t check over it and may be remove some more of the hardcoded elements.

**Comment by TimStallard** [comment]
Just made the repo public.
