### ISSUE TITLE
Fix debsums check + standardise NRPE configs

### ISSUE THREAD

**Issue by TimStallard** [sown/tasks#24]
The debsums check script (at least on some servers) is broken - the string result is compared as an integer, and the script will always return success regardless of the actual outcome.

As well as fixing the issue (I've already patched the script, though need to test it slightly more thoroughly), this seems like a good opportunity to standardise the NRPE configs on every server so they line up with the configs generated by ansible.

**Comment by drn05r** [comment]
Before starting this it may be worth installing Ansible on auth2 and checkout the Git repository of playbooks there rather than on monitor.

**Comment by TimStallard** [comment]
Servers to sort:
- [x] admin-dev
- [x] auth2
- [x] backup2
- [x] backup3
- [x] buildroot
- [x] buildroot-dev
- [x] data1
- [x] external-monitor
- [x] gw
- [x] gw2
- [x] marconi
- [x] monitor
- [x] monitor-new
- [x] radius2
- [x] vms
- [x] vpn-test
- [x] vpn2
- [x] wifimon
- [x] www
- [x] zepler-websdr

tunnelbroker also has the debsums check, but I don't think I have access and suspect the config might be even less standard there?

**Comment by TimStallard** [comment]
Now sorted on all servers, and I've written and deployed a check for systemd failed services on everything as well. Just need to tidy up and commit now.

Should make it much easier to deploy new checks on every host at once :)
