### ISSUE TITLE
Review ipv6_tunnelbroker repository to see if it can be made public

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#25]
We should have made this public some time ago but we need to make sure it is complete and sufficiently documented and does not contain any private information.  There was a hardcoded IPv6 address in an earlier commit, which is not a problem.  However, if there were any keys for CAs created they would need to be fully removed from the repository.

**Comment by pjb304** [comment]
Looks fine to me, a couple of corrections suggested in a pull request.

**Comment by drn05r** [comment]
Pull request merged and repository made public now two of us have cheked it.
