### ISSUE TITLE
Investigate why conntrackd active connections has started increasing so quickly

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#36]
Prior to rebooting gw and gw2 for the 4.15.0-60.67 kernel upgrade.  The number of active connections according to conntrackd increased fairly slowly (approx. 6000-7000 a day on gw2, which is currently primary) prior the upgrade up to (40,000-50,000) since.  

Both servers have since been rebooted to use the 4.15.0-62.69 kernel but with no change.

Currently "conntrackd -s" on gw2 shows 22,614 connections whilst "conntrack -C" only shows 673.

**Comment by TimStallard** [comment]
cron job was modified to clear conntrackd's state table and resync with the kernel's hourly rather than daily, it's stopped us hitting limits for now at least, underlying issue still needs investigating

**Comment by TimStallard** [comment]
Since migrating to nftables the number of states in conntrackd's table has been stable, and the cron job has been disabled for a while now. I suspect we've just stopped routing things asymmetrically for now - but either way, all looks good at the moment.
