### ISSUE TITLE
VMS templates creating VMs on wrong storage location

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#47]
CoreOS, Ubuntu 16.04.5 and Ubuntu 18.04.1 templates all had there storage location set to default rather than disks.  So a number of VMs have been created on the hosts main disk partition (default) rather than the one dedicated to guests (disks).  This has led to the host system almost running out of disk space,

**Comment by drn05r** [comment]
All templates have been updated to use the 'disks' rather than the 'default' storage location according to the Wok web interface.

**Comment by drn05r** [comment]
@TimStallard  has successfully copied the CoreOS VM to the appropriate location and updated the VM's metadata with virsh.  He checked it boots and deleted the old image and interfaces.

**Comment by TimStallard** [comment]
To migrate:
- [x] CoreOS - qcow2
- [x] zepler-websdr - vmdk
- [x] SOWN-VPN-Test - qcow2
- [x] wifimon - vmdk
- [x] monitor2 - vmdk
- [x] netbox - vmdk
- [x] jumpbox - vmdk

**Comment by TimStallard** [comment]
All migrated, should probably keep old disk images for a week or so in case of any issues, then clear them out.
May be worthwhile looking at dropping the libvirt "default" storage pool, and moving ISOs to the kimchi specific ISO one? Some VMs have ISOs attached in the old location, so would need to update config for that as well, or remove the ISOs from the VMs.

**Comment by TimStallard** [comment]
ISOs all removed from guests and moved to the Kimchi ISO storage pool now, and have deactivated the default pool. Just need to clean up VM disks soon now.

**Comment by TimStallard** [comment]
I've just removed all the old VM disks.
