### ISSUE TITLE
Add monitoring on ZFS pools

### ISSUE THREAD

**Issue by TimStallard** [sown/tasks#51]
Now that we're rebuilding backup servers on ZFS, we should monitor these pools, checking both pool health and free space.

Should be easy enough, we just need to check the following, and can work fine unprivileged via NRPE:
```console
tim@backup3:~$ zpool get health data -H -o value
ONLINE
tim@backup3:~$ zpool get capacity data -H -o value
1%
```

zed is also set up (on backup3 at least) and should email in the case of errors from scrubs, emails don't seem to be getting relayed properly so far though.

**Comment by TimStallard** [comment]
backup3 ran out of space today, so we should get round to doing this

I think @drn05r is looking at adding checks, otherwise probably one to do at the next workshop day

**Comment by drn05r** [comment]
I have added ZPOOL-HEALTH and ZPOOL-USAGE checks to both backup servers on both sown-monitor.ecs and monitor2.sown.
