### ISSUE TITLE
Migrate devices to correct IP range

### ISSUE THREAD

**Issue by trickeydan** [sown/tasks#53]
The following devices

- `odroid`
- `staff-wqm`
- `student-wqm`

This ticket is assigned to Tim because he said it needed doing and then ignored me saying that we should create a ticket.

**Comment by TimStallard** [comment]
those are chris' boxes

**Comment by TimStallard** [comment]
We need to decide to where in the SOWN subnet we want to move these, discuss this evening.

**Comment by TimStallard** [comment]
Allocated IPs 10.5.0.{249, 250, 251}

**Comment by TimStallard** [comment]
@cjsoftuk renumbered these last night
