### ISSUE TITLE
Rename servers

### ISSUE THREAD

**Issue by TimStallard** [sown/tasks#65]
Now that we've started using hostnames like `vms-b53-1`, we should move over other servers, eg as we move GW over to B53.

We'll first need to work out how to actually rename a server!
Things that come to mind:
- rename in netbox
- rebuild dns
- zfs rename dataset on backup2 and backup3
- mv dir in /var/lib/graphite/whisper/icinga2/ to keep monitoring graphs

If we're still using the admin system at this point:
- rename in node control
- ~~mv dir from hostname in /var/sown_backups/ on auth2 for backups~~
- somehow reshuffle bits of PNP on monitor (mv dir in `/usr/local/icinga/share/perfdata`)
- probably more things I'm not remembering

**Comment by TimStallard** [comment]
machines to rename:

- [x] `vms` -> `vms-b32-1`
- [x] `gw` -> `gw-b53-1`
- [x] `gw2` -> `gw-b32-1`
- [x] `backup2` -> `backup-b53-1`
- [x] `backup3` -> `backup-b32-1`

**Comment by drn05r** [comment]
There is a potential to get a couple of new (to SOWN servers).  They may be useful as replacement gateway servers as the hardware of the current gateway servers is quite old.  If that is the case it may be usefuk to keep the hostnames as gw-b53-1 and gw-b32-1 but cname them to gw-b53 and gw-b32 then build the new servers as gw-b53-2 and gw-b32-2

**Comment by drn05r** [comment]
DNS (internal and external) for vms / vms-b32-1 has already been updated it is just the hostname on the server itself that is left to update.

**Comment by drn05r** [comment]
gw-b32-1 has been further updated to gw-b32 and gw-b53-1 has been updated to gw-b53.  Appropriate DNS changes have also been made by iSolutions.  I think we have lost the Graphana graphs on monitor2 as I did not rename to merge in time but datastores on backups servers were modified to avoid duplicates.
