### ISSUE TITLE
Make a new shell server

### ISSUE THREAD

**Issue by trickeydan** [sown/tasks#69]
We currently ssh from auth2 to everywhere.

Let's not?

**Comment by drn05r** [comment]
We should use Jumpbox for this.  Maybe we should also repurpose data1, then we have redundancy in case VMS fails.  We could also setup a jumpbox on vms-b53-1.  However, we need to be able to sync stuff to all of these if we have more than one and they need to be standalone in case whatever does the syncing fails.

**Comment by drn05r** [comment]
@Tyler-Ward Has setup a new server on the IP address 10.5.0.209 and 152.78.103.165 and 2001:630:d0:f700::209.  

This looks to be working well although did seem to originally be on an IP address already in use (10.5.0.212) so this was moved to .209 and the IPv6 address updated correspondingly (see #85).

I have just put in an iSolutions ticket for SOWN DNS changes.  I forgot to mention this but will try to add once iSolutions has raised the ticket.

**Comment by drn05r** [comment]
Once we are happy with the login server we may want a duplicate login server running on VMS-B32-1, so that we always have one login server online even if we are rebooting a VM host.

**Comment by Tyler-Ward** [comment]
login2 now exists so this is complete
