### ISSUE TITLE
Increase /boot partition on VMS

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#76]
The /boot partition is now barely big enough for three kernels.  We need to increase this so it can easily store at least 5 kernels at once.

**Comment by TimStallard** [comment]
we don't have much room to work with at the start of the disk on VMS:

```
root@vms:~# lsblk
NAME                                                                   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                                                      8:0    0   1.8T  0 disk 
├─sda1                                                                   8:1    0   512M  0 part /boot/efi
├─sda2                                                                   8:2    0   244M  0 part /boot
```

/boot/efi is relatively empty, only contains a copy of grub, so I think we could safely delete both partitions, then re-create a much smaller ESP (50MB perhaps?), and allocate the rest of that space to /boot

**Comment by TimStallard** [comment]
I've repartitioned VMS so that it now BIOS boots (like the rest of our servers), and has a much bigger /boot:
```
sown@vms:~$ df -h /boot
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       728M  151M  524M  23% /boot
```
This also means our PXE / rescue setup works, which didn't before with EFI booting
