### ISSUE TITLE
Ensure regular cycling of ZFS snapshots on backup servers to stop running out of space

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#80]
Although there is still capacity to remove old style backups to free space on the backup servers for a while yet.  We need to look at the cycling of ZFS snapshots so that disk usage on backup servers stays fairly constant.

**Comment by TimStallard** [comment]
we should be able to just modify how many snapshots we keep - it's set in `/opt/sown/backup/backup/config.py` - https://github.com/sown/backup/blob/master/backup/config.example.py#L5

I guess the other option is we make it smarter, so it keeps exactly enough snapshots to keep our disk usage at a certain level

one to discuss tomorrow

**Comment by TimStallard** [comment]
I've reduced our retention of monthly snapshots on backup2 to 12 months (was previously 24), let's see how it goes tonight

**Comment by drn05r** [comment]
@TimStallard Also updated backup3 to have the schedule a few days later.  Both backup servers seem to be keeping a reasonably stable level of disk usage since this change in the 70-75% range.  

I think this can be resolved.  Although we should keep and eye on this to make sure it does not creep up too much over time.
