### ISSUE TITLE
Move www to Sown VM host

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#83]
www.sown.org.uk (sown-www.ecs.soton.ac.uk) is hosted on iSolutions VMWare cluster.  It cannot be upgraded as the /boot partition does not have enough space for newer kernels.  Expanding /boot is possible but would require iSolutions help.  It would be easily to make www a VM hosted on one of SOWN's VM host servers.  This should be done by doing a bare metal restore from backups.

www.sown.org.uk is still on an ECS DMZ IP.  So we will need to get iSolutions to update the DNS to point at whatever SOWN public IP address we use for the VM we create.

**Comment by TimStallard** [comment]
This has been done as part of the new website
